### ISSUE TITLE
nodata 之后    下拉刷新有新数据了，， 怎么 nodata(false)？

### ISSUE THREAD

**Issue by panwenhua** [jy03078959/vue-drapload#4]
nodata 之后    下拉刷新有新数据了，， 怎么 nodata(false)？  文档 不全啊
me.ascroll.resetload()和me.ascroll.resetload(true)有啥区别

**Comment by jy03078959** [comment]
noData() 当加载更多数据（drapload-down对应方法）的时候没有数据后可以调用该方法。这时加载跟多组件状态会改为无数据状态
noData() 的相反方法。有个叫 hasData() 的。

**Comment by panwenhua** [comment]
THKS
